[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.9.2"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "^v0.11.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "0.31.5"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "~0.14.1"

[[override]]
  name = "golang.org/x/crypto"
  revision = "ff983b9c42bc9fbf91556e191cc8efb585c16908"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"
